<?php

/**
 * BaseInstance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $config_file
 * @property string $status_file
 * @property Doctrine_Collection $VPNSessions
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getConfigFile()  Returns the current record's "config_file" value
 * @method string              getStatusFile()  Returns the current record's "status_file" value
 * @method Doctrine_Collection getVPNSessions() Returns the current record's "VPNSessions" collection
 * @method Instance            setId()          Sets the current record's "id" value
 * @method Instance            setName()        Sets the current record's "name" value
 * @method Instance            setConfigFile()  Sets the current record's "config_file" value
 * @method Instance            setStatusFile()  Sets the current record's "status_file" value
 * @method Instance            setVPNSessions() Sets the current record's "VPNSessions" collection
 * 
 * @package    VPNmon
 * @subpackage model
 * @author     Severin Schols <severin@schols.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('instance');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('config_file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status_file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VPNSession as VPNSessions', array(
             'local' => 'id',
             'foreign' => 'instance_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}