<?php

/**
 * Certificate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    VPNmon
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Certificate extends BaseCertificate
{
	public function getTotalDuration() {
		$duration = 0;
		
		foreach ($this->getVPNSessions() as $session) {
			$duration += $session->getDuration();
		}
		
		return Formatter::secondsFormat($duration);
	}
	
	public function getTotalBytesReceived() {
		$bytes = 0;
		
		foreach ($this->getVPNSessions() as $session) {
			$bytes += $session->getBytesReceived();
		}
		
		return Formatter::bytesFormat($bytes);
	}

	public function getTotalBytesSent() {
		$bytes = 0;
		
		foreach ($this->getVPNSessions() as $session) {
			$bytes += $session->getBytesSent();
		}
		
		return Formatter::bytesFormat($bytes);
	}
}