<?php

/**
 * InstanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Instance');
    }
}